AWSTemplateFormatVersion: "2010-09-09"                                                      
Description: "Laboratorio 3"                                                                
Resources:                                                                                  
    Ec2Instance:                                                                            
        Type: AWS::EC2::Instance                                                            
        Properties:                                                                         
            DisableApiTermination: true                                                     
            ImageId: ami-041feb57c611358bd                                                  
            InstanceType: t2.micro                                                          
            SubnetId: subnet-0c4f6c5dd01a8f0ac                                              
            SecurityGroupIds:                                                               
                - !Ref SecurityGroup                                                        
            Tags:                                                                           
                - Key: Name                                                                 
                  Value: Web-Server                                                         
            UserData:                                                                       
                Fn::Base64: |                                                               
                    #!/bin/bash                                                             
                    dnf install -y httpd                                                    
                    systemctl enable httpd                                                  
                    systemctl start httpd                                                   
                    echo '<html><h1>Cloudformation Rulez!!</h1></html>' > /var/www/html/index.html                                                                                      
    SecurityGroup:                                                                          
        Type: AWS::EC2::SecurityGroup                                                       
        Properties:                                                                         
            GroupDescription: "Security group for my web server"                            
            GroupName: "Web server security group"                                          
            SecurityGroupIngress:                                                           
                - IpProtocol: tcp                                                           
                  FromPort: 80                                                              
                  ToPort: 80                                                                
                  CidrIp: "0.0.0.0/0"                                                       
            VpcId: vpc-05673a283b831cee0